version: '3.6'

services:
  gateway:
    command: npm run dev
    build: .
    environment:
      - AUTH_API_ENDPOINT=auth:3003
      - DATA_API_ENDPOINT=api:3000
      - GRAPHQL_API_ENDPOINT=graphql:3004
      - STREAM_API_ENDPOINT=stream:3001
    volumes:
      - .:/app
    networks:
      - net
    ports:
      - '8080:8080'
  auth:
    command: npm run dev
    build: ../soundplace-auth
    env_file:
      - .secrets/database.env
      - .secrets/youtube.env
      - .secrets/jwt.env
    environment:
      - API_URL=http://localhost:8080
      - DATA_API_ENDPOINT=api:3000
      - CLIENT_URL=http://localhost:9000
      - DATABASE_ENDPOINT=db
    volumes:
      - ../soundplace-auth:/app
    networks:
      - net
    ports:
      - '3003:3003'
  api:
    build: ../soundplace-api
    command: npm run dev
    env_file:
      - .secrets/database.env
    environment:
      - AUTH_API_ENDPOINT=auth:3003
      - DATABASE_ENDPOINT=db
    volumes:
      - ../soundplace-api:/app
    networks:
      - net
    ports:
      - '3000:3000'
  graphql:
    build: ../soundplace-graphql
    command: npm run dev
    env_file:
      - .secrets/database.env
    environment:
      - AUTH_API_ENDPOINT=auth:3003
      - DATABASE_ENDPOINT=db
    volumes:
      - ../soundplace-graphql:/app
    networks:
      - net
    ports:
      - '3004:3004'
  stream:
    build: ../soundplace-stream
    volumes:
      - ../soundplace-stream:/app
    networks:
      - net
    ports:
      - '3001:3001'
  db:
    build: ../soundplace-db
    env_file:
      - .secrets/database.env
    volumes:
      - ../soundplace-db:/app
    networks:
      - net
    ports:
      - '5432:5432'
networks:
  net:
    driver: bridge

